# Generated by Django 2.2.6 on 2019-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_client', models.CharField(max_length=48, verbose_name='Название компании')),
                ('project_title', models.CharField(max_length=36, verbose_name='Название проекта')),
                ('project_type', models.CharField(max_length=36, verbose_name='Тип проекта')),
                ('project_description', models.TextField(verbose_name='Описание проекта')),
                ('project_body', models.TextField(verbose_name='Тело проекта')),
                ('project_cover', models.ImageField(max_length=120, upload_to='img', verbose_name='Обложка проекта')),
                ('pub_date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
