# Generated by Django 2.2.6 on 2019-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_client', models.CharField(max_length=48, verbose_name='Название компании')),
                ('project_title', models.CharField(max_length=36, verbose_name='Название проекта')),
                ('project_type', models.CharField(max_length=36, verbose_name='Тип проекта')),
                ('project_description', models.TextField(verbose_name='Описание проекта')),
                ('project_body', models.TextField(verbose_name='Тело проекта')),
                ('project_cover', models.ImageField(upload_to='upload', verbose_name='Обложка проекта')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
