# Generated by Django 2.2.6 on 2019-11-04 13:19

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
    ]
